-- Run once in the Supabase SQL editor for an existing installation.
create table if not exists public.collections (
    id bigint generated by default as identity primary key,
    title text not null,
    slug text not null,
    medium text not null check (medium in ('photograph', 'drawing', 'poem')),
    description text,
    cover_item_id bigint references public.portfolio_items(id) on delete set null,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (medium, slug)
);

create table if not exists public.collection_items (
    collection_id bigint not null references public.collections(id) on delete cascade,
    portfolio_item_id bigint not null references public.portfolio_items(id) on delete cascade,
    sort_order integer not null default 0,
    primary key (collection_id, portfolio_item_id)
);

alter table public.collections enable row level security;
alter table public.collection_items enable row level security;

drop policy if exists "collections are publicly readable" on public.collections;
create policy "collections are publicly readable"
    on public.collections for select using (true);

drop policy if exists "collection items are publicly readable" on public.collection_items;
create policy "collection items are publicly readable"
    on public.collection_items for select using (true);

-- Writes are made by the server-only service-role key.
