-- Run this once in the Supabase SQL editor.
create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text not null,
    display_name text,
    role text not null default 'viewer' check (role in ('admin', 'viewer')),
    created_at timestamptz not null default now()
);

create table if not exists public.portfolio_items (
    id bigint generated by default as identity primary key,
    title text not null,
    type text not null check (type in ('photograph', 'drawing', 'poem')),
    image text,
    description text,
    poem text,
    thoughts text,
    image_width integer not null default 4 check (image_width > 0),
    image_height integer not null default 3 check (image_height > 0),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.likes (
    item_id bigint not null references public.portfolio_items(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (item_id, user_id)
);

create table if not exists public.comments (
    id bigint generated by default as identity primary key,
    item_id bigint not null references public.portfolio_items(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    author_name text not null,
    body text not null check (char_length(body) between 1 and 1000),
    created_at timestamptz not null default now()
);

create table if not exists public.hero_gallery_settings (
    id integer primary key check (id = 1),
    layout_key text not null default 'editorial'
        check (layout_key in ('editorial', 'balanced', 'featured-strip')),
    updated_at timestamptz not null default now()
);

create table if not exists public.hero_gallery_slots (
    slot_key text primary key
        check (slot_key in ('featured', 'secondary', 'tertiary', 'quaternary')),
    portfolio_item_id bigint references public.portfolio_items(id) on delete set null,
    sort_order integer not null check (sort_order between 1 and 4),
    updated_at timestamptz not null default now()
);

insert into public.hero_gallery_settings (id, layout_key)
values (1, 'editorial')
on conflict (id) do nothing;

insert into public.hero_gallery_slots (slot_key, portfolio_item_id, sort_order)
values
    ('featured', null, 1),
    ('secondary', null, 2),
    ('tertiary', null, 3),
    ('quaternary', null, 4)
on conflict (slot_key) do nothing;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
    insert into public.profiles (id, email, display_name, role)
    values (
        new.id,
        coalesce(new.email, ''),
        coalesce(new.raw_user_meta_data ->> 'display_name', split_part(coalesce(new.email, ''), '@', 1)),
        'viewer'
    )
    on conflict (id) do nothing;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.portfolio_items enable row level security;
alter table public.likes enable row level security;
alter table public.comments enable row level security;
alter table public.hero_gallery_settings enable row level security;
alter table public.hero_gallery_slots enable row level security;

create policy "public content is readable"
    on public.portfolio_items for select using (true);
create policy "profiles are readable by owner"
    on public.profiles for select to authenticated using (auth.uid() = id);
create policy "comments are publicly readable"
    on public.comments for select using (true);
create policy "likes are publicly readable"
    on public.likes for select using (true);
create policy "hero settings are publicly readable"
    on public.hero_gallery_settings for select using (true);
create policy "hero slots are publicly readable"
    on public.hero_gallery_slots for select using (true);

-- Application writes use the server-only service-role key. Never expose it in browser code.
-- Promote the first administrator after they register:
-- update public.profiles set role = 'admin' where email = 'you@example.com';

-- Optional starter content. It runs only when the collection is empty.
insert into public.portfolio_items
    (title, type, image, description, poem, thoughts, image_width, image_height)
select *
from (values
    (
        'Joseph — Study in Light',
        'photograph',
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=1000&fit=crop',
        'A portrait capturing Joseph in natural morning light.',
        'Light finds the edges,\nsilent and persistent,\nrevealing what was always there.',
        'Sometimes the best portraits are about being present with another person.',
        4,
        5
    ),
    (
        'Untitled Drawing',
        'drawing',
        'https://images.unsplash.com/photo-1578925078519-cf21a4eae3f7?w=1000&h=700&fit=crop',
        'Ink on paper. A study of form and negative space.',
        null,
        'The wavering line and unexpected smudge are the most honest parts.',
        10,
        7
    ),
    (
        'Absence',
        'poem',
        null,
        'A meditation on presence and what we notice when we stop looking.',
        'I am learning to sit with silence.\nNot the silence of absence,\nbut the silence of listening.',
        null,
        1,
        1
    ),
    (
        'Joseph — Hands',
        'photograph',
        'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=600&h=900&fit=crop',
        'A detail study. Hands say more than faces sometimes.',
        null,
        'Details are where intimacy lives.',
        2,
        3
    ),
    (
        'Studies in Ink',
        'drawing',
        'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=900&h=600&fit=crop',
        'Quick sketches exploring movement and gesture.',
        null,
        null,
        3,
        2
    ),
    (
        'Before Autumn',
        'photograph',
        'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&h=1200&fit=crop',
        'Taken just before everything changes.',
        'Everything is leaving.\nEverything is arriving.\nI am standing in between,\nwatchful.',
        null,
        2,
        3
    )
) as seed(title, type, image, description, poem, thoughts, image_width, image_height)
where not exists (select 1 from public.portfolio_items);

-- Public image storage bucket for admin uploads.
insert into storage.buckets (id, name, public)
values ('portfolio', 'portfolio', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public read portfolio images" on storage.objects;
create policy "Public read portfolio images"
    on storage.objects for select
    using (bucket_id = 'portfolio');

drop policy if exists "Service role can manage portfolio images" on storage.objects;
create policy "Service role can manage portfolio images"
    on storage.objects for all
    using (bucket_id = 'portfolio')
    with check (bucket_id = 'portfolio');
